/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DebtsIndexRouteImport } from './routes/debts/index'
import { Route as DebtsSettledRouteImport } from './routes/debts/settled'
import { Route as DebtsNewRouteImport } from './routes/debts/new'
import { Route as DebtsIdRouteImport } from './routes/debts/$id'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsIndexRoute = DebtsIndexRouteImport.update({
  id: '/debts/',
  path: '/debts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsSettledRoute = DebtsSettledRouteImport.update({
  id: '/debts/settled',
  path: '/debts/settled',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsNewRoute = DebtsNewRouteImport.update({
  id: '/debts/new',
  path: '/debts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DebtsIdRoute = DebtsIdRouteImport.update({
  id: '/debts/$id',
  path: '/debts/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/debts/$id': typeof DebtsIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/debts/settled': typeof DebtsSettledRoute
  '/debts/': typeof DebtsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/debts/$id': typeof DebtsIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/debts/settled': typeof DebtsSettledRoute
  '/debts': typeof DebtsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/debts/$id': typeof DebtsIdRoute
  '/debts/new': typeof DebtsNewRoute
  '/debts/settled': typeof DebtsSettledRoute
  '/debts/': typeof DebtsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/debts/$id'
    | '/debts/new'
    | '/debts/settled'
    | '/debts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/debts/$id'
    | '/debts/new'
    | '/debts/settled'
    | '/debts'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/notifications'
    | '/profile'
    | '/register'
    | '/debts/$id'
    | '/debts/new'
    | '/debts/settled'
    | '/debts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  DebtsIdRoute: typeof DebtsIdRoute
  DebtsNewRoute: typeof DebtsNewRoute
  DebtsSettledRoute: typeof DebtsSettledRoute
  DebtsIndexRoute: typeof DebtsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/': {
      id: '/debts/'
      path: '/debts'
      fullPath: '/debts/'
      preLoaderRoute: typeof DebtsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/settled': {
      id: '/debts/settled'
      path: '/debts/settled'
      fullPath: '/debts/settled'
      preLoaderRoute: typeof DebtsSettledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/new': {
      id: '/debts/new'
      path: '/debts/new'
      fullPath: '/debts/new'
      preLoaderRoute: typeof DebtsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debts/$id': {
      id: '/debts/$id'
      path: '/debts/$id'
      fullPath: '/debts/$id'
      preLoaderRoute: typeof DebtsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  DebtsIdRoute: DebtsIdRoute,
  DebtsNewRoute: DebtsNewRoute,
  DebtsSettledRoute: DebtsSettledRoute,
  DebtsIndexRoute: DebtsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
