services:
  db:
    image: postgres:17-alpine
    container_name: debts-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: debts_app
      POSTGRES_USER: debts_user
      POSTGRES_PASSWORD: debts_pass123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: